In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#from pandasql import sqldf

df_article = pd.read_csv('articles.csv')
df_article

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105537,953450001,953450,5pk regular Placement1,302,Socks,Socks & Tights,1010014,Placement print,9,Black,...,Socks Bin,F,Menswear,3,Menswear,26,Men Underwear,1021,Socks and Tights,Socks in a fine-knit cotton blend with a small...
105538,953763001,953763,SPORT Malaga tank,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,2,H&M+,1005,Jersey Fancy,Loose-fitting sports vest top in ribbed fast-d...
105539,956217002,956217,Cartwheel dress,265,Dress,Garment Full body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,"Short, A-line dress in jersey with a round nec..."
105540,957375001,957375,CLAIRE HAIR CLAW,72,Hair clip,Accessories,1010016,Solid,9,Black,...,Small Accessories,D,Divided,2,Divided,52,Divided Accessories,1019,Accessories,Large plastic hair claw.
105541,959461001,959461,Lounge dress,265,Dress,Garment Full body,1010016,Solid,11,Off White,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,Calf-length dress in ribbed jersey made from a...

In [2]:
df_article.columns

Index(['article_id', 'product_code', 'prod_name', 'product_type_no',
       'product_type_name', 'product_group_name', 'graphical_appearance_no',
       'graphical_appearance_name', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_value_name',
       'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'index_group_name', 'section_no', 'section_name',
       'garment_group_no', 'garment_group_name', 'detail_desc'],
      dtype='object')

In [3]:
df_art = df_article

df_art.drop(['product_code', 'prod_name', 'product_type_no',
       'graphical_appearance_no', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'section_no', 'garment_group_no', 'detail_desc'], inplace=True, axis=1)

df_art

,article_id,product_type_name,product_group_name,graphical_appearance_name,perceived_colour_value_name,index_group_name,section_name,garment_group_name
0,108775015,Vest top,Garment Upper body,Solid,Dark,Ladieswear,Womens Everyday Basics,Jersey Basic
1,108775044,Vest top,Garment Upper body,Solid,Light,Ladieswear,Womens Everyday Basics,Jersey Basic
2,108775051,Vest top,Garment Upper body,Stripe,Dusty Light,Ladieswear,Womens Everyday Basics,Jersey Basic
3,110065001,Bra,Underwear,Solid,Dark,Ladieswear,Womens Lingerie,"Under-, Nightwear"
4,110065002,Bra,Underwear,Solid,Light,Ladieswear,Womens Lingerie,"Under-, Nightwear"
...,...,...,...,...,...,...,...,...
105537,953450001,Socks,Socks & Tights,Placement print,Dark,Menswear,Men Underwear,Socks and Tights
105538,953763001,Vest top,Garment Upper body,Solid,Dark,Ladieswear,H&M+,Jersey Fancy
105539,956217002,Dress,Garment Full body,Solid,Dark,Ladieswear,Womens Trend,Jersey Fancy
105540,957375001,Hair clip,Accessories,Solid,Dark,Divided,Divided Accessories,Accessories
105541,959461001,Dress,Garment Full body,Solid,Dusty Light,Ladieswear,Womens Trend,Jersey Fancy

In [4]:
df_art['graphical_appearance_name'].value_counts()

Solid                  49747
All over pattern       17165
Melange                 5938
Stripe                  4990
Denim                   4842
Front print             3215
Placement print         3098
Check                   2178
Colour blocking         1830
Lace                    1513
Other structure         1502
Application/3D          1341
Embroidery              1165
Mixed solid/pattern     1132
Glittering/Metallic      958
Jacquard                 830
Sequin                   806
Dot                      681
Treatment                586
Other pattern            515
Contrast                 376
Metallic                 346
Chambray                 322
Slub                     153
Transparent               86
Mesh                      86
Neps                      66
Unknown                   52
Argyle                    15
Hologram                   8
Name: graphical_appearance_name, dtype: int64

In [5]:
df_art['product_group_name'].value_counts()

Garment Upper body       42741
Garment Lower body       19812
Garment Full body        13292
Accessories              11158
Underwear                 5490
Shoes                     5283
Swimwear                  3127
Socks & Tights            2442
Nightwear                 1899
Unknown                    121
Underwear/nightwear         54
Cosmetic                    49
Bags                        25
Items                       17
Furniture                   13
Garment and Shoe care        9
Stationery                   5
Interior textile             3
Fun                          2
Name: product_group_name, dtype: int64

In [6]:
df_art['section_name'].value_counts()

Womens Everyday Collection        7295
Divided Collection                7124
Baby Essentials & Complements     4932
Kids Girl                         4469
Young Girl                        3899
Womens Lingerie                   3598
Girls Underwear & Basics          3490
Womens Tailoring                  3376
Kids Boy                          3328
Womens Small accessories          3270
Womens Casual                     2725
Kids Outerwear                    2665
Womens Trend                      2622
Divided Projects                  2364
Young Boy                         2352
H&M+                              2337
Men Underwear                     2322
Mama                              2266
Kids & Baby Shoes                 2142
Boys Underwear & Basics           2034
Womens Shoes                      2026
Ladies H&M Sport                  1894
Womens Swimwear, beachwear        1839
Contemporary Smart                1778
Baby Girl                         1760
Divided Accessories               1732
Kids Accessories, Swimwear & D    1731
Divided Basics                    1723
Baby Boy                          1717
Womens Big accessories            1665
Womens Everyday Basics            1581
Womens Nightwear, Socks & Tigh    1566
Contemporary Casual               1560
Contemporary Street               1490
Men Suits & Tailoring             1428
Men Accessories                   1337
Womens Premium                    1270
Ladies Denim                      1101
Divided Selected                   991
Men H&M Sport                      872
Womens Jackets                     829
Special Collections                682
Men Shoes                          645
Mens Outerwear                     629
Kids Sports                        626
Collaborations                     559
Denim Men                          521
Men Edition                        330
Men Project                        298
Divided Asia keys                  280
Kids Local Relevance               192
Men Other 2                        190
Divided Complements Other           35
EQ Divided                          26
Men Other                           25
Ladies Other                         4
Name: section_name, dtype: int64

In [7]:
df_art['garment_group_name'].value_counts()

Jersey Fancy                     21445
Accessories                      11519
Jersey Basic                      8126
Knitwear                          7490
Under-, Nightwear                 7441
Trousers                          6727
Blouses                           5838
Shoes                             5145
Dresses Ladies                    4874
Outdoor                           4501
Unknown                           3873
Trousers Denim                    3100
Swimwear                          2787
Socks and Tights                  2272
Shirts                            2116
Woven/Jersey/Knitted mix Baby     1965
Shorts                            1559
Dresses/Skirts girls              1541
Skirts                            1254
Special Offers                    1061
Dressed                            908
Name: garment_group_name, dtype: int64

In [8]:
df_art['product_type_name'].value_counts().iloc[:20]

Trousers            11169
Dress               10362
Sweater              9302
T-shirt              7904
Top                  4155
Blouse               3979
Jacket               3940
Shorts               3939
Shirt                3405
Vest top             2991
Underwear bottom     2748
Skirt                2696
Hoodie               2356
Bra                  2212
Socks                1889
Leggings/Tights      1878
Sneakers             1621
Cardigan             1550
Hat/beanie           1349
Garment Set          1320
Name: product_type_name, dtype: int64

In [9]:
temp = df_art['graphical_appearance_name'].value_counts() <= 2000
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_graphical_appearance"] = df_art["graphical_appearance_name"].apply(lambda x : 'other' if x in mask else x)

In [10]:
df_art['modified_graphical_appearance'].value_counts()

Solid               49747
All over pattern    17165
other               14369
Melange              5938
Stripe               4990
Denim                4842
Front print          3215
Placement print      3098
Check                2178
Name: modified_graphical_appearance, dtype: int64

In [11]:
temp = df_art['product_group_name'].value_counts() <= 2000
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_product_group"] = df_art["product_group_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_product_group'].value_counts()

Garment Upper body    42741
Garment Lower body    19812
Garment Full body     13292
Accessories           11158
Underwear              5490
Shoes                  5283
Swimwear               3127
Socks & Tights         2442
other                  2197
Name: modified_product_group, dtype: int64

In [12]:
temp = df_art['section_name'].value_counts() <= 3328
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_section"] = df_art["section_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_section'].value_counts()

other                            67359
Womens Everyday Collection        7295
Divided Collection                7124
Baby Essentials & Complements     4932
Kids Girl                         4469
Young Girl                        3899
Womens Lingerie                   3598
Girls Underwear & Basics          3490
Womens Tailoring                  3376
Name: modified_section, dtype: int64

In [13]:
temp = df_art['garment_group_name'].value_counts() <= 4874
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_garment_group"] = df_art["garment_group_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_garment_group'].value_counts()

other                31811
Jersey Fancy         21445
Accessories          11519
Jersey Basic          8126
Knitwear              7490
Under-, Nightwear     7441
Trousers              6727
Blouses               5838
Shoes                 5145
Name: modified_garment_group, dtype: int64

In [14]:
#keeping 20 most frequent
temp = df_art['product_type_name'].value_counts() <= 1320
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_product_type"] = df_art["product_type_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_product_type'].value_counts()

other               26097
Trousers            11169
Dress               10362
Sweater              9302
T-shirt              7904
Top                  4155
Blouse               3979
Jacket               3940
Shorts               3939
Shirt                3405
Vest top             2991
Underwear bottom     2748
Skirt                2696
Hoodie               2356
Bra                  2212
Socks                1889
Leggings/Tights      1878
Sneakers             1621
Cardigan             1550
Hat/beanie           1349
Name: modified_product_type, dtype: int64

In [15]:
df_art.columns

Index(['article_id', 'product_type_name', 'product_group_name',
       'graphical_appearance_name', 'perceived_colour_value_name',
       'index_group_name', 'section_name', 'garment_group_name',
       'modified_graphical_appearance', 'modified_product_group',
       'modified_section', 'modified_garment_group', 'modified_product_type'],
      dtype='object')

In [16]:
df_art.drop(['graphical_appearance_name', 'product_group_name', 'section_name', 'garment_group_name', 'product_type_name'], inplace=True, axis=1)

df_art

,article_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type
0,108775015,Dark,Ladieswear,Solid,Garment Upper body,other,Jersey Basic,Vest top
1,108775044,Light,Ladieswear,Solid,Garment Upper body,other,Jersey Basic,Vest top
2,108775051,Dusty Light,Ladieswear,Stripe,Garment Upper body,other,Jersey Basic,Vest top
3,110065001,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",Bra
4,110065002,Light,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",Bra
...,...,...,...,...,...,...,...,...
105537,953450001,Dark,Menswear,Placement print,Socks & Tights,other,other,Socks
105538,953763001,Dark,Ladieswear,Solid,Garment Upper body,other,Jersey Fancy,Vest top
105539,956217002,Dark,Ladieswear,Solid,Garment Full body,other,Jersey Fancy,Dress
105540,957375001,Dark,Divided,Solid,Accessories,other,Accessories,other
105541,959461001,Dusty Light,Ladieswear,Solid,Garment Full body,other,Jersey Fancy,Dress

# CUSTOMER

In [17]:
df_customer = pd.read_csv('customers.csv')
df_customer

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...
...,...,...,...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,NaN,NaN,ACTIVE,NONE,24.0,7aa399f7e669990daba2d92c577b52237380662f36480b...
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,NaN,NaN,ACTIVE,NONE,21.0,3f47f1279beb72215f4de557d950e0bfa73789d24acb5e...
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,1.0,ACTIVE,Regularly,21.0,4563fc79215672cd6a863f2b4bf56b8f898f2d96ed590e...
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,1.0,ACTIVE,Regularly,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,NaN,NaN,PRE-CREATE,NONE,65.0,0a1a03306fb2f62164c2a439b38c0caa64b40deaae8687...

In [18]:
df_customer.columns

Index(['customer_id', 'FN', 'Active', 'club_member_status',
       'fashion_news_frequency', 'age', 'postal_code'],
      dtype='object')

In [19]:
df_cust = df_customer

df_cust.drop(['FN', 'fashion_news_frequency', 'postal_code'], inplace=True, axis=1)

df_cust

,customer_id,Active,club_member_status,age
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,ACTIVE,49.0
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,ACTIVE,25.0
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,ACTIVE,24.0
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,ACTIVE,54.0
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,ACTIVE,52.0
...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,NaN,ACTIVE,24.0
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,NaN,ACTIVE,21.0
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,ACTIVE,21.0
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,ACTIVE,18.0
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,NaN,PRE-CREATE,65.0

In [20]:
df_cust['club_member_status'] = df_cust['club_member_status'].fillna('N/A')

In [21]:
df_cust['Active'] = df_cust['Active'].fillna(0)
df_cust["age"] = df_cust["age"].fillna(df_cust["age"].mean())

In [22]:
df_cust = pd.concat([df_cust.drop(columns=["club_member_status"]), pd.get_dummies(df_cust["club_member_status"])], axis=1)

In [126]:
df_cust

,customer_id,Active,age,ACTIVE,LEFT CLUB,N/A,PRE-CREATE
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0.0,49.0,1,0,0,0
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0.0,25.0,1,0,0,0
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0.0,24.0,1,0,0,0
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0.0,54.0,1,0,0,0
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,52.0,1,0,0,0
...,...,...,...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,0.0,24.0,1,0,0,0
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,0.0,21.0,1,0,0,0
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,21.0,1,0,0,0
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,18.0,1,0,0,0
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,0.0,65.0,0,0,0,1

# TRANSACTION

In [177]:
df_transaction = pd.read_csv('transactions_train.csv')

In [89]:
df_transaction = df_transaction.sort_values("customer_id")

## Converting t-dat to Datetime in Transactions Dataset

In [178]:
df_transaction["t_dat"] = pd.to_datetime(df_transaction["t_dat"])

## Merging Tranactions with Articles

In [179]:
df_combined = df_transaction.merge(df_art, on=["article_id"], how="inner")
df_combined

,t_dat,customer_id,article_id,price,sales_channel_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
1,2018-09-20,3681748607f3287d2c3a65e00bb5fb153de30e9becf158...,663713001,0.049475,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
2,2018-09-20,4ef5967ff17bf474bffebe5b16bd54878e1d4105f7b4ed...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
3,2018-09-20,6b7b10d2d47516c82a6f97332478dab748070f09693f09...,663713001,0.050831,1,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
4,2018-09-20,8ac137752bbe914aa4ae6ad007a9a0c5b67a1ab2b2d474...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
...,...,...,...,...,...,...,...,...,...,...,...,...
31788319,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,860135008,0.038119,1,Medium Dusty,Menswear,Check,Garment Upper body,other,other,Shirt
31788320,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,539060028,0.016017,1,Bright,Baby/Children,All over pattern,Garment Upper body,other,Jersey Basic,Hoodie
31788321,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,539060028,0.016000,1,Bright,Baby/Children,All over pattern,Garment Upper body,other,Jersey Basic,Hoodie
31788322,2020-09-22,ee9c048de16034be4aa95c91adce7f7bda442e6528406e...,810737015,0.033881,2,Light,Baby/Children,Front print,other,Baby Essentials & Complements,"Under-, Nightwear",other
31788323,2020-09-22,f79e372e21c1359dfebc7da0bf7f321d55e47b3275c351...,533261032,0.033881,2,Medium Dusty,Baby/Children,Solid,Garment Upper body,Baby Essentials & Complements,Jersey Basic,other

In [94]:
# for each customer find a random date to base the data point from
random_time = df_combined[df_combined.t_dat < "2020-09-15"].groupby("customer_id").agg({"t_dat": lambda x: x.sample(1)})

In [95]:
random_time.head()

                                                        t_dat
customer_id
32fe1032067fe86fe454716524146fe7947caa7608414f1... 2019-01-13
32fe148504dced0d743692fa2c0cd168990b6a9f20ba756... 2019-03-09
32fe25f404af8b953793e20adaf10f34762017802688339... 2019-05-02
32fe26fab07dd13b5f55393b32a2d5d01fad69dba11e7ca... 2019-11-03
32fe2d246a9806e85c00b22681ed61b2126ad36caee379e... 2020-06-08

In [96]:
random_time = random_time.rename(columns={"t_dat": "pivot"}).reset_index()

## Merging Pivot Dates with Combined (Transaction+Articles) Dataset

In [97]:
df_combined_random = df_combined.merge(random_time, on="customer_id")

In [98]:
df_combined_random.head()

,t_dat,customer_id,article_id,price,sales_channel_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type,pivot
0,2019-06-26,32fe1032067fe86fe454716524146fe7947caa7608414f...,408875002,0.006763,2,Dusty Light,Divided,Melange,Garment Upper body,other,Jersey Basic,Vest top,2019-01-13
1,2018-09-30,32fe1032067fe86fe454716524146fe7947caa7608414f...,572280002,0.007610,2,Dark,Baby/Children,Front print,Garment Upper body,Young Girl,Jersey Fancy,Sweater,2019-01-13
2,2019-06-26,32fe1032067fe86fe454716524146fe7947caa7608414f...,612481002,0.023712,2,Medium Dusty,Ladieswear,Denim,Garment Lower body,Womens Everyday Collection,other,Shorts,2019-01-13
3,2020-02-06,32fe1032067fe86fe454716524146fe7947caa7608414f...,706016001,0.029254,2,Dark,Divided,Solid,Garment Lower body,Divided Collection,Trousers,Trousers,2019-01-13
4,2020-03-27,32fe1032067fe86fe454716524146fe7947caa7608414f...,673396002,0.013542,2,Dark,Ladieswear,Solid,Accessories,other,Accessories,other,2019-01-13

In [99]:
# converting sales channel id to text to be able to do the one hot encoding
df_combined_random.sales_channel_id = df_combined_random.sales_channel_id.astype(str)

In [100]:
# columns that are used to featurize the clients
feature_columns = ["sales_channel_id", "perceived_colour_value_name",
            "index_group_name", "modified_graphical_appearance",
            "modified_product_group", "modified_section", "modified_garment_group",
            "modified_product_type"
           ]
# Forming the names of columns after one-hot-encoding
dummy_cols = []
for col in feature_columns:
    dummy_cols.extend([col + "_" + x for x in df_combined_random[col].unique()])
all_article_ids = list(df_article.article_id.unique())

In [101]:
# for each customer look at the transactions before the pivot time and find the characteristics of those transactions to
# get an understanding of what the customer likes, for example, what fraction of the articles the customer bought are
# dark. Then look at the 7 day period after the pivot time and consider the articles that the customer bought as positive
# target and sample randomly some articles that the customer never bought in their history as negative targets. Sample
# as many negative targets as there are positive ones
def process(df):
    before = df[df["t_dat"] <= df["pivot"]]
    before_7d = df[(df["t_dat"] <= df["pivot"]) & (df["t_dat"] > df["pivot"] - pd.Timedelta(7, "days"))]
    after = df[(df["t_dat"] > df["pivot"]) & (df["t_dat"] < df["pivot"] + pd.Timedelta(7, "days"))]
    after["label"] = 1
    after = after[["article_id", "label"]]
    if len(after) == 0:
        return None
    negs = random.sample(all_article_ids,len(after))
    negs = [i for i in negs if i not in df.article_id]
    negs_df = after.copy()
    negs_df["article_id"] = negs
    negs_df["label"] = 0
    after = pd.concat([after, negs_df], axis=0)
    means = pd.get_dummies(before[feature_columns]).mean(axis=0)
    means["avg_price"] = before["price"].mean()
    means_df = means.to_frame().transpose()
    means_df = means_df.reindex(columns=dummy_cols).fillna(0.0)
    means_df["num_purchase"] = len(before)
    # 7d calculations
    means_7d = pd.get_dummies(before_7d[feature_columns]).mean(axis=0)
    means_df_7d = means_7d.to_frame().transpose()
    means_df_7d.columns = means_df_7d.columns + "_7d"
    means_df_7d = means_df_7d.reindex(columns=[col + "_7d" for col in dummy_cols]).fillna(0.0)
    means_df_7d["num_purchase_7d"] = len(before_7d)
    means_df_7d["avg_price_7d"] = before_7d["price"].mean()
    means_df_combined = pd.concat([means_df, means_df_7d.fillna(0)], axis=1)
    combined = pd.concat([means_df_combined] * len(after), axis=0)
    combined["article_id"] = after["article_id"].values
    combined["label"] = after["label"].values
    
    return combined.reset_index(drop=True)

In [102]:
final_data = df_combined_random.groupby("customer_id").apply(process).reset_index(level=1, drop=True).reset_index()

In [113]:
one_hot_article = pd.get_dummies(df_article[feature_columns[1:]])

In [114]:
one_hot_article["article_id"] = df_article["article_id"]
one_hot_article.columns = one_hot_article.columns + "_target"

In [131]:
final_data_ = final_data.merge(df_cust, on="customer_id").merge(one_hot_article, left_on="article_id", right_on="article_id_target")

In [132]:
final_data_ = final_data_.drop(columns=["article_id_target", "article_id"])

In [545]:
final_data_.head()

,customer_id,sales_channel_id_1,sales_channel_id_2,perceived_colour_value_name_Dark,perceived_colour_value_name_MediumDusty,perceived_colour_value_name_DustyLight,perceived_colour_value_name_Bright,perceived_colour_value_name_Light,perceived_colour_value_name_Medium,perceived_colour_value_name_Unknown,...,modified_product_type_Skirt_target,modified_product_type_Sneakers_target,modified_product_type_Socks_target,modified_product_type_Sweater_target,modified_product_type_Tshirt_target,modified_product_type_Top_target,modified_product_type_Trousers_target,modified_product_type_Underwearbottom_target,modified_product_type_Vesttop_target,modified_product_type_other_target
0,0000d6c053fc8f9389d4565051f12402d5774aa4a9d2e5...,0.000000,1.000000,0.333333,0.500000,0.000000,0.000000,0.166667,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
1,001b9b6b1b2e37a2c24370041b884c99e14b3611693db1...,0.000000,1.000000,0.500000,0.000000,0.166667,0.000000,0.333333,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
2,026deff8ade4058f7709f5a4d3640beccfec2076ea2fd1...,0.100000,0.900000,0.600000,0.000000,0.200000,0.200000,0.000000,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
3,04d8c6e1c8aef3aad8eb2f33d9fcb74faeaf22799eaf32...,0.000000,1.000000,0.428571,0.142857,0.142857,0.071429,0.214286,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0583f24e7af774461ab00bb3292fc4bf36d94909022e07...,0.166667,0.833333,0.500000,0.000000,0.000000,0.000000,0.333333,0.166667,0.0,...,0,0,0,0,0,0,0,0,0,0

## Training

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.metrics import accuracy_score

In [141]:
import re
final_data_ = final_data_.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

### split data

In [142]:
X = final_data_.drop(columns=["label", "customer_id"])
y = final_data_["label"]
X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.2)

First try bagging classifer

In [314]:
model1 = BaggingClassifier(DecisionTreeClassifier())
model1.fit(X_tr, y_tr)

BaggingClassifier(base_estimator=DecisionTreeClassifier())

In [315]:
accuracy_score(y_val, model1.predict(X_val))

0.7841474046323131

Good accuracy!

In [316]:
%%timeit
model1.predict(X_val)

2.06 s ± 15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

But running it on the test data takes a lot of time!

In [137]:
import lightgbm as lgb

In [547]:
model = lgb.LGBMClassifier(learning_rate=0.09,max_depth=-5,n_estimators=1000, num_leaves=70)
model.fit(X_tr, y_tr, eval_set=[(X_val,y_val),(X_tr,y_tr)],
          verbose=20,eval_metric=["binary_error"])

[20]	training's binary_error: 0.24662	training's binary_logloss: 0.509179	valid_0's binary_error: 0.246996	valid_0's binary_logloss: 0.508656
[40]	training's binary_error: 0.233897	training's binary_logloss: 0.478009	valid_0's binary_error: 0.23571	valid_0's binary_logloss: 0.478567
[60]	training's binary_error: 0.226464	training's binary_logloss: 0.464	valid_0's binary_error: 0.228894	valid_0's binary_logloss: 0.465894
[80]	training's binary_error: 0.220875	training's binary_logloss: 0.454233	valid_0's binary_error: 0.222962	valid_0's binary_logloss: 0.457519
[100]	training's binary_error: 0.216768	training's binary_logloss: 0.447434	valid_0's binary_error: 0.220689	valid_0's binary_logloss: 0.452243
[120]	training's binary_error: 0.214353	training's binary_logloss: 0.443103	valid_0's binary_error: 0.219357	valid_0's binary_logloss: 0.449511
[140]	training's binary_error: 0.211693	training's binary_logloss: 0.439298	valid_0's binary_error: 0.217773	valid_0's binary_logloss: 0.447336
[160]	training's binary_error: 0.209275	training's binary_logloss: 0.435872	valid_0's binary_error: 0.216459	valid_0's binary_logloss: 0.445452
[180]	training's binary_error: 0.206894	training's binary_logloss: 0.432678	valid_0's binary_error: 0.21547	valid_0's binary_logloss: 0.443798
[200]	training's binary_error: 0.205074	training's binary_logloss: 0.430041	valid_0's binary_error: 0.214498	valid_0's binary_logloss: 0.442633
[220]	training's binary_error: 0.203134	training's binary_logloss: 0.427262	valid_0's binary_error: 0.213661	valid_0's binary_logloss: 0.441276
[240]	training's binary_error: 0.201136	training's binary_logloss: 0.424418	valid_0's binary_error: 0.212966	valid_0's binary_logloss: 0.4399
[260]	training's binary_error: 0.199333	training's binary_logloss: 0.421609	valid_0's binary_error: 0.212418	valid_0's binary_logloss: 0.438498
[280]	training's binary_error: 0.197644	training's binary_logloss: 0.419259	valid_0's binary_error: 0.211735	valid_0's binary_logloss: 0.437475
[300]	training's binary_error: 0.195401	training's binary_logloss: 0.41652	valid_0's binary_error: 0.21091	valid_0's binary_logloss: 0.436186
[320]	training's binary_error: 0.193892	training's binary_logloss: 0.414489	valid_0's binary_error: 0.210221	valid_0's binary_logloss: 0.435491
[340]	training's binary_error: 0.19208	training's binary_logloss: 0.411882	valid_0's binary_error: 0.209473	valid_0's binary_logloss: 0.434254
[360]	training's binary_error: 0.190577	training's binary_logloss: 0.409547	valid_0's binary_error: 0.209126	valid_0's binary_logloss: 0.433166
[380]	training's binary_error: 0.189265	training's binary_logloss: 0.407427	valid_0's binary_error: 0.208625	valid_0's binary_logloss: 0.432338
[400]	training's binary_error: 0.187683	training's binary_logloss: 0.405189	valid_0's binary_error: 0.208054	valid_0's binary_logloss: 0.431481
[420]	training's binary_error: 0.186163	training's binary_logloss: 0.403139	valid_0's binary_error: 0.207282	valid_0's binary_logloss: 0.430732
[440]	training's binary_error: 0.185097	training's binary_logloss: 0.401436	valid_0's binary_error: 0.207241	valid_0's binary_logloss: 0.430298
[460]	training's binary_error: 0.183633	training's binary_logloss: 0.399288	valid_0's binary_error: 0.206799	valid_0's binary_logloss: 0.429396
[480]	training's binary_error: 0.181959	training's binary_logloss: 0.396995	valid_0's binary_error: 0.206068	valid_0's binary_logloss: 0.42845
[500]	training's binary_error: 0.180402	training's binary_logloss: 0.394755	valid_0's binary_error: 0.205715	valid_0's binary_logloss: 0.427625
[520]	training's binary_error: 0.179039	training's binary_logloss: 0.392929	valid_0's binary_error: 0.205208	valid_0's binary_logloss: 0.426998
[540]	training's binary_error: 0.177435	training's binary_logloss: 0.390766	valid_0's binary_error: 0.204466	valid_0's binary_logloss: 0.426232
[560]	training's binary_error: 0.176094	training's binary_logloss: 0.388798	valid_0's binary_error: 0.203977	valid_0's binary_logloss: 0.425596
[580]	training's binary_error: 0.175017	training's binary_logloss: 0.387246	valid_0's binary_error: 0.203589	valid_0's binary_logloss: 0.425206
[600]	training's binary_error: 0.173689	training's binary_logloss: 0.385378	valid_0's binary_error: 0.20327	valid_0's binary_logloss: 0.424564
[620]	training's binary_error: 0.172646	training's binary_logloss: 0.383798	valid_0's binary_error: 0.202952	valid_0's binary_logloss: 0.424121
[640]	training's binary_error: 0.171478	training's binary_logloss: 0.382148	valid_0's binary_error: 0.202575	valid_0's binary_logloss: 0.423692
[660]	training's binary_error: 0.170344	training's binary_logloss: 0.380472	valid_0's binary_error: 0.202334	valid_0's binary_logloss: 0.423242
[680]	training's binary_error: 0.169073	training's binary_logloss: 0.378805	valid_0's binary_error: 0.20211	valid_0's binary_logloss: 0.422796
[700]	training's binary_error: 0.167959	training's binary_logloss: 0.377054	valid_0's binary_error: 0.201951	valid_0's binary_logloss: 0.422232
[720]	training's binary_error: 0.166716	training's binary_logloss: 0.375306	valid_0's binary_error: 0.201544	valid_0's binary_logloss: 0.42173
[740]	training's binary_error: 0.165572	training's binary_logloss: 0.373759	valid_0's binary_error: 0.201332	valid_0's binary_logloss: 0.421344
[760]	training's binary_error: 0.16427	training's binary_logloss: 0.37212	valid_0's binary_error: 0.201191	valid_0's binary_logloss: 0.420865
[780]	training's binary_error: 0.163148	training's binary_logloss: 0.370471	valid_0's binary_error: 0.200808	valid_0's binary_logloss: 0.42034
[800]	training's binary_error: 0.162081	training's binary_logloss: 0.368916	valid_0's binary_error: 0.200602	valid_0's binary_logloss: 0.419938
[820]	training's binary_error: 0.160977	training's binary_logloss: 0.367577	valid_0's binary_error: 0.200284	valid_0's binary_logloss: 0.419682
[840]	training's binary_error: 0.159837	training's binary_logloss: 0.365916	valid_0's binary_error: 0.200119	valid_0's binary_logloss: 0.419237
[860]	training's binary_error: 0.158777	training's binary_logloss: 0.364289	valid_0's binary_error: 0.200084	valid_0's binary_logloss: 0.418707
[880]	training's binary_error: 0.157855	training's binary_logloss: 0.363056	valid_0's binary_error: 0.199819	valid_0's binary_logloss: 0.418403
[900]	training's binary_error: 0.156745	training's binary_logloss: 0.36143	valid_0's binary_error: 0.199677	valid_0's binary_logloss: 0.417872
[920]	training's binary_error: 0.15565	training's binary_logloss: 0.359895	valid_0's binary_error: 0.199306	valid_0's binary_logloss: 0.417446
[940]	training's binary_error: 0.154578	training's binary_logloss: 0.358533	valid_0's binary_error: 0.199112	valid_0's binary_logloss: 0.417122
[960]	training's binary_error: 0.153556	training's binary_logloss: 0.357071	valid_0's binary_error: 0.198882	valid_0's binary_logloss: 0.416793
[980]	training's binary_error: 0.152525	training's binary_logloss: 0.355616	valid_0's binary_error: 0.198623	valid_0's binary_logloss: 0.416438
[1000]	training's binary_error: 0.151462	training's binary_logloss: 0.354225	valid_0's binary_error: 0.198582	valid_0's binary_logloss: 0.416217

LGBMClassifier(learning_rate=0.09, max_depth=-5, n_estimators=1000,
               num_leaves=70)

Model valid error rate is good 0.198 which is equal to around 80% accuracy

In [328]:
%%timeit
model.predict(X_val)

670 ms ± 47.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Still very slow!

## process the test data

In [180]:
df_combined = df_combined.sort_values(["customer_id", "t_dat"])

In [191]:
df_combined.sales_channel_id = df_combined.sales_channel_id.astype(str)

In [192]:
# We kinda do the same thing as when training but now we consider the last purchase of the customer as our pivot
# and we don't have targets in here because all inventory is our target hence we don't need to add article features
# separately
def process_test(df):
    before_7d = df[df["t_dat"] > df["t_dat"].iloc[-1] - pd.Timedelta(7, "days")]
    means = pd.get_dummies(df[feature_columns]).mean(axis=0)
    means["avg_price"] = df["price"].mean()
    means_df = means.to_frame().transpose()
    means_df = means_df.reindex(columns=dummy_cols).fillna(0.0)
    means_df["num_purchase"] = len(df)
    # 7d calculations
    means_7d = pd.get_dummies(before_7d[feature_columns]).mean(axis=0)
    means_df_7d = means_7d.to_frame().transpose()
    means_df_7d.columns = means_df_7d.columns + "_7d"
    means_df_7d = means_df_7d.reindex(columns=[col + "_7d" for col in dummy_cols]).fillna(0.0)
    means_df_7d["num_purchase_7d"] = len(before_7d)
    means_df_7d["avg_price_7d"] = before_7d["price"].mean()
    means_df_combined = pd.concat([means_df, means_df_7d.fillna(0)], axis=1)
    return means_df_combined.reset_index(drop=True)

In [200]:
%%time
test_data = df_combined.groupby("customer_id").apply(process_test).reset_index(level=1, drop=True).reset_index()

CPU times: user 5h 39min 57s, sys: 4min 1s, total: 5h 43min 59s
Wall time: 5h 45min 59s

In [282]:
test_data = test_data.merge(df_cust, on="customer_id")

In [283]:
test_data = test_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [285]:
test_data = test_data[["customer_id"] + list(X_tr.columns[:-69]) ]

In [ ]:
customer_ids = test_data["customer_id"].values
customer_features = test_data.drop(columns=["customer_id"]).values
article_features = one_hot_article.drop(columns=["article_id_target"]).values
article_ids = one_hot_article["article_id_target"].values

In [350]:
customer_features.shape

(1362281, 151)

## Let's try Neural Networks

In [546]:
import pytorch_lightning as pl
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset

In [461]:
# In this network we pass the customer features through 2 layers and the article features through another 2 layers
# at the end, we dot product the resulting customer and article representation together
class Model(pl.LightningModule):
    def __init__(self, customer_dim, article_dim, hidden_dim):
        super(Model, self).__init__()
        self.customer_layer1 = torch.nn.Linear(customer_dim, hidden_dim)
        self.customer_layer2 = torch.nn.Linear(hidden_dim, hidden_dim)
        self.article_layer1 = torch.nn.Linear(article_dim, hidden_dim)
        self.article_layer2 = torch.nn.Linear(hidden_dim, hidden_dim)
    def forward(self, x, article_features):
        x = self.customer_layer2(F.relu(self.customer_layer1(x)))
        y = self.article_layer2(F.relu(self.article_layer1(article_features)))
        return (x * y).sum(-1)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

    def training_step(self, train_batch, batch_idx):
        x, z, y = train_batch
        loss = F.binary_cross_entropy_with_logits(self.forward(x, z), y)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, z, y = val_batch
        loss = F.binary_cross_entropy_with_logits(self.forward(x, z), y)
        self.log('val_loss', loss, on_epoch=True, on_step=False, prog_bar=True)

In [462]:
# Dataset needed for training
class dataset(Dataset):
    def __init__(self, features, labels, num_customer_features):
        self.customer_features = torch.tensor(features[:, :num_customer_features], dtype=torch.float32)
        self.article_features = torch.tensor(features[:, num_customer_features:], dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.float32)
    def __len__(self):
        return len(self.customer_features)
    def __getitem__(self, i):
        return self.customer_features[i, :], self.article_features[i, :], self.labels[i]

train_set = dataset(X_tr.values, y_tr.values, 151)
val_set = dataset(X_val.values, y_val.values, 151)
train_loader = DataLoader(train_set, batch_size=32, num_workers=16, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, num_workers=16)

In [466]:
# model
model = Model(151, 69, 50)

# training
trainer = pl.Trainer(gpus=0, max_epochs=4)
trainer.fit(model, train_loader, val_loader)

GPU available: False, used: False
TPU available: None, using: 0 TPU cores

  | Name            | Type   | Params
-------------------------------------------
0 | customer_layer1 | Linear | 7.6 K
1 | customer_layer2 | Linear | 2.6 K
2 | article_layer1  | Linear | 3.5 K
3 | article_layer2  | Linear | 2.6 K
-------------------------------------------
16.2 K    Trainable params
0         Non-trainable params
16.2 K    Total params

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validation sanity check', layout=Layout…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Training', layout=Layout(flex='2'), max…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validating', layout=Layout(flex='2'), m…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validating', layout=Layout(flex='2'), m…

1

In [467]:
accuracy_score(y_val, model(a, b) > 0)

0.7705049362644613

Not a bad accuracy

Now that the network is trained, let's calculate the predictions on the test set

In [488]:
# article representation (ar) does not change from customer to customer so let's compute it once
ar = model.article_layer2(F.relu(model.article_layer1(torch.tensor(article_features, dtype=torch.float32)))).T

In [503]:
customer_features_tensor = torch.tensor(customer_features, dtype=torch.float32)

In [522]:
# let's batch the test data into batches of 1000 and calculate the predictions of the network manually
# Then find the most probablt articles for each client and save them as predictions
bs = 1000
i = 0
preds = {}
while i < len(customer_features_tensor):
    print(f"at batch {i}")
    cids = customer_ids[i: i + bs]
    cf = customer_features_tensor[i: i + bs]
    cr = model.customer_layer2(F.relu(model.customer_layer1(cf)))
    dots = cr @ ar
    top_articles = torch.argsort(dots, descending=True)[:, :12]
    for cid, recs in zip(cids, top_articles):
        preds[cid] = " ".join(["0" + str(x) for x in article_ids[recs]])
    i += bs

at batch 0
at batch 1000
at batch 2000
at batch 3000
at batch 4000
at batch 5000
at batch 6000
at batch 7000
at batch 8000
at batch 9000
at batch 10000
at batch 11000
at batch 12000
at batch 13000
at batch 14000
at batch 15000
at batch 16000
at batch 17000
at batch 18000
at batch 19000
at batch 20000
at batch 21000
at batch 22000
at batch 23000
at batch 24000
at batch 25000
at batch 26000
at batch 27000
at batch 28000
at batch 29000
at batch 30000
at batch 31000
at batch 32000
at batch 33000
at batch 34000
at batch 35000
at batch 36000
at batch 37000
at batch 38000
at batch 39000
at batch 40000
at batch 41000
at batch 42000
at batch 43000
at batch 44000
at batch 45000
at batch 46000
at batch 47000
at batch 48000
at batch 49000
at batch 50000
at batch 51000
at batch 52000
at batch 53000
at batch 54000
at batch 55000
at batch 56000
at batch 57000
at batch 58000
at batch 59000
at batch 60000
at batch 61000
at batch 62000
at batch 63000
at batch 64000
at batch 65000
at batch 66000
at batch 67000
at batch 68000
at batch 69000
at batch 70000
at batch 71000
at batch 72000
at batch 73000
at batch 74000
at batch 75000
at batch 76000
at batch 77000
at batch 78000
at batch 79000
at batch 80000
at batch 81000
at batch 82000
at batch 83000
at batch 84000
at batch 85000
at batch 86000
at batch 87000
at batch 88000
at batch 89000
at batch 90000
at batch 91000
at batch 92000
at batch 93000
at batch 94000
at batch 95000
at batch 96000
at batch 97000
at batch 98000
at batch 99000
at batch 100000
at batch 101000
at batch 102000
at batch 103000
at batch 104000
at batch 105000
at batch 106000
at batch 107000
at batch 108000
at batch 109000
at batch 110000
at batch 111000
at batch 112000
at batch 113000
at batch 114000
at batch 115000
at batch 116000
at batch 117000
at batch 118000
at batch 119000
at batch 120000
at batch 121000
at batch 122000
at batch 123000
at batch 124000
at batch 125000
at batch 126000
at batch 127000
at batch 128000
at batch 129000
at batch 130000
at batch 131000
at batch 132000
at batch 133000
at batch 134000
at batch 135000
at batch 136000
at batch 137000
at batch 138000
at batch 139000
at batch 140000
at batch 141000
at batch 142000
at batch 143000
at batch 144000
at batch 145000
at batch 146000
at batch 147000
at batch 148000
at batch 149000
at batch 150000
at batch 151000
at batch 152000
at batch 153000
at batch 154000
at batch 155000
at batch 156000
at batch 157000
at batch 158000
at batch 159000
at batch 160000
at batch 161000
at batch 162000
at batch 163000
at batch 164000
at batch 165000
at batch 166000
at batch 167000
at batch 168000
at batch 169000
at batch 170000
at batch 171000
at batch 172000
at batch 173000
at batch 174000
at batch 175000
at batch 176000
at batch 177000
at batch 178000
at batch 179000
at batch 180000
at batch 181000
at batch 182000
at batch 183000
at batch 184000
at batch 185000
at batch 186000
at batch 187000
at batch 188000
at batch 189000
at batch 190000
at batch 191000
at batch 192000
at batch 193000
at batch 194000
at batch 195000
at batch 196000
at batch 197000
at batch 198000
at batch 199000
at batch 200000
at batch 201000
at batch 202000
at batch 203000
at batch 204000
at batch 205000
at batch 206000
at batch 207000
at batch 208000
at batch 209000
at batch 210000
at batch 211000
at batch 212000
at batch 213000
at batch 214000
at batch 215000
at batch 216000
at batch 217000
at batch 218000
at batch 219000
at batch 220000
at batch 221000
at batch 222000
at batch 223000
at batch 224000
at batch 225000
at batch 226000
at batch 227000
at batch 228000
at batch 229000
at batch 230000
at batch 231000
at batch 232000
at batch 233000
at batch 234000
at batch 235000
at batch 236000
at batch 237000
at batch 238000
at batch 239000
at batch 240000
at batch 241000
at batch 242000
at batch 243000
at batch 244000
at batch 245000
at batch 246000
at batch 247000
at batch 248000
at batch 249000
at batch 250000
at batch 251000
at batch 252000
at batch 253000
at batch 254000
at batch 255000
at batch 256000
at batch 257000
at batch 258000
at batch 259000
at batch 260000
at batch 261000
at batch 262000
at batch 263000
at batch 264000
at batch 265000
at batch 266000
at batch 267000
at batch 268000
at batch 269000
at batch 270000
at batch 271000
at batch 272000
at batch 273000
at batch 274000
at batch 275000
at batch 276000
at batch 277000
at batch 278000
at batch 279000
at batch 280000
at batch 281000
at batch 282000
at batch 283000
at batch 284000
at batch 285000
at batch 286000
at batch 287000
at batch 288000
at batch 289000
at batch 290000
at batch 291000
at batch 292000
at batch 293000
at batch 294000
at batch 295000
at batch 296000
at batch 297000
at batch 298000
at batch 299000
at batch 300000
at batch 301000
at batch 302000
at batch 303000
at batch 304000
at batch 305000
at batch 306000
at batch 307000
at batch 308000
at batch 309000
at batch 310000
at batch 311000
at batch 312000
at batch 313000
at batch 314000
at batch 315000
at batch 316000
at batch 317000
at batch 318000
at batch 319000
at batch 320000
at batch 321000
at batch 322000
at batch 323000
at batch 324000
at batch 325000
at batch 326000
at batch 327000
at batch 328000
at batch 329000
at batch 330000
at batch 331000
at batch 332000
at batch 333000
at batch 334000
at batch 335000
at batch 336000
at batch 337000
at batch 338000
at batch 339000
at batch 340000
at batch 341000
at batch 342000
at batch 343000
at batch 344000
at batch 345000
at batch 346000
at batch 347000
at batch 348000
at batch 349000
at batch 350000
at batch 351000
at batch 352000
at batch 353000
at batch 354000
at batch 355000
at batch 356000
at batch 357000
at batch 358000
at batch 359000
at batch 360000
at batch 361000
at batch 362000
at batch 363000
at batch 364000
at batch 365000
at batch 366000
at batch 367000
at batch 368000
at batch 369000
at batch 370000
at batch 371000
at batch 372000
at batch 373000
at batch 374000
at batch 375000
at batch 376000
at batch 377000
at batch 378000
at batch 379000
at batch 380000
at batch 381000
at batch 382000
at batch 383000
at batch 384000
at batch 385000
at batch 386000
at batch 387000
at batch 388000
at batch 389000
at batch 390000
at batch 391000
at batch 392000
at batch 393000
at batch 394000
at batch 395000
at batch 396000
at batch 397000
at batch 398000
at batch 399000
at batch 400000
at batch 401000
at batch 402000
at batch 403000
at batch 404000
at batch 405000
at batch 406000
at batch 407000
at batch 408000
at batch 409000
at batch 410000
at batch 411000
at batch 412000
at batch 413000
at batch 414000
at batch 415000
at batch 416000
at batch 417000
at batch 418000
at batch 419000
at batch 420000
at batch 421000
at batch 422000
at batch 423000
at batch 424000
at batch 425000
at batch 426000
at batch 427000
at batch 428000
at batch 429000
at batch 430000
at batch 431000
at batch 432000
at batch 433000
at batch 434000
at batch 435000
at batch 436000
at batch 437000
at batch 438000
at batch 439000
at batch 440000
at batch 441000
at batch 442000
at batch 443000
at batch 444000
at batch 445000
at batch 446000
at batch 447000
at batch 448000
at batch 449000
at batch 450000
at batch 451000
at batch 452000
at batch 453000
at batch 454000
at batch 455000
at batch 456000
at batch 457000
at batch 458000
at batch 459000
at batch 460000
at batch 461000
at batch 462000
at batch 463000
at batch 464000
at batch 465000
at batch 466000
at batch 467000
at batch 468000
at batch 469000
at batch 470000
at batch 471000
at batch 472000
at batch 473000
at batch 474000
at batch 475000
at batch 476000
at batch 477000
at batch 478000
at batch 479000
at batch 480000
at batch 481000
at batch 482000
at batch 483000
at batch 484000
at batch 485000
at batch 486000
at batch 487000
at batch 488000
at batch 489000
at batch 490000
at batch 491000
at batch 492000
at batch 493000
at batch 494000
at batch 495000
at batch 496000
at batch 497000
at batch 498000
at batch 499000
at batch 500000
at batch 501000
at batch 502000
at batch 503000
at batch 504000
at batch 505000
at batch 506000
at batch 507000
at batch 508000
at batch 509000
at batch 510000
at batch 511000
at batch 512000
at batch 513000
at batch 514000
at batch 515000
at batch 516000
at batch 517000
at batch 518000
at batch 519000

at batch 520000
at batch 521000
at batch 522000
at batch 523000
at batch 524000
at batch 525000
at batch 526000
at batch 527000
at batch 528000
at batch 529000
at batch 530000
at batch 531000
at batch 532000
at batch 533000
at batch 534000
at batch 535000
at batch 536000
at batch 537000
at batch 538000
at batch 539000
at batch 540000
at batch 541000
at batch 542000
at batch 543000
at batch 544000
at batch 545000
at batch 546000
at batch 547000
at batch 548000
at batch 549000
at batch 550000
at batch 551000
at batch 552000
at batch 553000
at batch 554000
at batch 555000
at batch 556000
at batch 557000
at batch 558000
at batch 559000
at batch 560000
at batch 561000
at batch 562000
at batch 563000
at batch 564000
at batch 565000
at batch 566000
at batch 567000
at batch 568000
at batch 569000
at batch 570000
at batch 571000
at batch 572000
at batch 573000
at batch 574000
at batch 575000
at batch 576000
at batch 577000
at batch 578000
at batch 579000
at batch 580000
at batch 581000
at batch 582000
at batch 583000
at batch 584000
at batch 585000
at batch 586000
at batch 587000
at batch 588000
at batch 589000
at batch 590000
at batch 591000
at batch 592000
at batch 593000
at batch 594000
at batch 595000
at batch 596000
at batch 597000
at batch 598000
at batch 599000
at batch 600000
at batch 601000
at batch 602000
at batch 603000
at batch 604000
at batch 605000
at batch 606000
at batch 607000
at batch 608000
at batch 609000
at batch 610000
at batch 611000
at batch 612000
at batch 613000
at batch 614000
at batch 615000
at batch 616000
at batch 617000
at batch 618000
at batch 619000
at batch 620000
at batch 621000
at batch 622000
at batch 623000
at batch 624000
at batch 625000
at batch 626000
at batch 627000
at batch 628000
at batch 629000
at batch 630000
at batch 631000
at batch 632000
at batch 633000
at batch 634000
at batch 635000
at batch 636000
at batch 637000
at batch 638000
at batch 639000
at batch 640000
at batch 641000
at batch 642000
at batch 643000
at batch 644000
at batch 645000
at batch 646000
at batch 647000
at batch 648000
at batch 649000
at batch 650000
at batch 651000
at batch 652000
at batch 653000
at batch 654000
at batch 655000
at batch 656000
at batch 657000
at batch 658000
at batch 659000
at batch 660000
at batch 661000
at batch 662000
at batch 663000
at batch 664000
at batch 665000
at batch 666000
at batch 667000
at batch 668000
at batch 669000
at batch 670000
at batch 671000
at batch 672000
at batch 673000
at batch 674000
at batch 675000
at batch 676000
at batch 677000
at batch 678000
at batch 679000
at batch 680000
at batch 681000
at batch 682000
at batch 683000
at batch 684000
at batch 685000
at batch 686000
at batch 687000
at batch 688000
at batch 689000
at batch 690000
at batch 691000
at batch 692000
at batch 693000
at batch 694000
at batch 695000
at batch 696000
at batch 697000
at batch 698000
at batch 699000
at batch 700000
at batch 701000
at batch 702000
at batch 703000
at batch 704000
at batch 705000
at batch 706000
at batch 707000
at batch 708000
at batch 709000
at batch 710000
at batch 711000
at batch 712000
at batch 713000
at batch 714000
at batch 715000
at batch 716000
at batch 717000
at batch 718000
at batch 719000
at batch 720000
at batch 721000
at batch 722000
at batch 723000
at batch 724000
at batch 725000
at batch 726000
at batch 727000
at batch 728000
at batch 729000
at batch 730000
at batch 731000
at batch 732000
at batch 733000
at batch 734000
at batch 735000
at batch 736000
at batch 737000
at batch 738000
at batch 739000
at batch 740000
at batch 741000
at batch 742000
at batch 743000
at batch 744000
at batch 745000
at batch 746000
at batch 747000
at batch 748000
at batch 749000
at batch 750000
at batch 751000
at batch 752000
at batch 753000
at batch 754000
at batch 755000
at batch 756000
at batch 757000
at batch 758000
at batch 759000
at batch 760000
at batch 761000
at batch 762000
at batch 763000
at batch 764000
at batch 765000
at batch 766000
at batch 767000
at batch 768000
at batch 769000
at batch 770000
at batch 771000
at batch 772000
at batch 773000
at batch 774000
at batch 775000
at batch 776000
at batch 777000
at batch 778000
at batch 779000
at batch 780000
at batch 781000
at batch 782000
at batch 783000
at batch 784000
at batch 785000
at batch 786000
at batch 787000
at batch 788000
at batch 789000
at batch 790000
at batch 791000
at batch 792000
at batch 793000
at batch 794000
at batch 795000
at batch 796000
at batch 797000
at batch 798000
at batch 799000
at batch 800000
at batch 801000
at batch 802000
at batch 803000
at batch 804000
at batch 805000
at batch 806000
at batch 807000
at batch 808000
at batch 809000
at batch 810000
at batch 811000
at batch 812000
at batch 813000
at batch 814000
at batch 815000
at batch 816000
at batch 817000
at batch 818000
at batch 819000
at batch 820000
at batch 821000
at batch 822000
at batch 823000
at batch 824000
at batch 825000
at batch 826000
at batch 827000
at batch 828000
at batch 829000
at batch 830000
at batch 831000
at batch 832000
at batch 833000
at batch 834000
at batch 835000
at batch 836000
at batch 837000
at batch 838000
at batch 839000
at batch 840000
at batch 841000
at batch 842000
at batch 843000
at batch 844000
at batch 845000
at batch 846000
at batch 847000
at batch 848000
at batch 849000
at batch 850000
at batch 851000
at batch 852000
at batch 853000
at batch 854000
at batch 855000
at batch 856000
at batch 857000
at batch 858000
at batch 859000
at batch 860000
at batch 861000
at batch 862000
at batch 863000
at batch 864000
at batch 865000
at batch 866000
at batch 867000
at batch 868000
at batch 869000
at batch 870000
at batch 871000
at batch 872000
at batch 873000
at batch 874000
at batch 875000
at batch 876000
at batch 877000
at batch 878000
at batch 879000
at batch 880000
at batch 881000
at batch 882000
at batch 883000
at batch 884000
at batch 885000
at batch 886000
at batch 887000
at batch 888000
at batch 889000
at batch 890000
at batch 891000
at batch 892000
at batch 893000
at batch 894000
at batch 895000
at batch 896000
at batch 897000
at batch 898000
at batch 899000
at batch 900000
at batch 901000
at batch 902000
at batch 903000
at batch 904000
at batch 905000
at batch 906000
at batch 907000
at batch 908000
at batch 909000
at batch 910000
at batch 911000
at batch 912000
at batch 913000
at batch 914000
at batch 915000
at batch 916000
at batch 917000
at batch 918000
at batch 919000
at batch 920000
at batch 921000
at batch 922000
at batch 923000
at batch 924000
at batch 925000
at batch 926000
at batch 927000
at batch 928000
at batch 929000
at batch 930000
at batch 931000
at batch 932000
at batch 933000
at batch 934000
at batch 935000
at batch 936000
at batch 937000
at batch 938000
at batch 939000
at batch 940000
at batch 941000
at batch 942000
at batch 943000
at batch 944000
at batch 945000
at batch 946000
at batch 947000
at batch 948000
at batch 949000
at batch 950000
at batch 951000
at batch 952000
at batch 953000
at batch 954000
at batch 955000
at batch 956000
at batch 957000
at batch 958000
at batch 959000
at batch 960000
at batch 961000
at batch 962000
at batch 963000
at batch 964000
at batch 965000
at batch 966000
at batch 967000
at batch 968000
at batch 969000
at batch 970000
at batch 971000
at batch 972000
at batch 973000
at batch 974000
at batch 975000
at batch 976000
at batch 977000
at batch 978000
at batch 979000
at batch 980000
at batch 981000
at batch 982000
at batch 983000
at batch 984000
at batch 985000
at batch 986000
at batch 987000
at batch 988000
at batch 989000
at batch 990000
at batch 991000
at batch 992000
at batch 993000
at batch 994000
at batch 995000
at batch 996000
at batch 997000
at batch 998000
at batch 999000
at batch 1000000
at batch 1001000
at batch 1002000
at batch 1003000
at batch 1004000
at batch 1005000
at batch 1006000
at batch 1007000
at batch 1008000
at batch 1009000
at batch 1010000
at batch 1011000
at batch 1012000
at batch 1013000
at batch 1014000
at batch 1015000
at batch 1016000
at batch 1017000
at batch 1018000
at batch 1019000
at batch 1020000
at batch 1021000
at batch 1022000
at batch 1023000
at batch 1024000
at batch 1025000
at batch 1026000
at batch 1027000
at batch 1028000
at batch 1029000
at batch 1030000

at batch 1031000
at batch 1032000
at batch 1033000
at batch 1034000
at batch 1035000
at batch 1036000
at batch 1037000
at batch 1038000
at batch 1039000
at batch 1040000
at batch 1041000
at batch 1042000
at batch 1043000
at batch 1044000
at batch 1045000
at batch 1046000
at batch 1047000
at batch 1048000
at batch 1049000
at batch 1050000
at batch 1051000
at batch 1052000
at batch 1053000
at batch 1054000
at batch 1055000
at batch 1056000
at batch 1057000
at batch 1058000
at batch 1059000
at batch 1060000
at batch 1061000
at batch 1062000
at batch 1063000
at batch 1064000
at batch 1065000
at batch 1066000
at batch 1067000
at batch 1068000
at batch 1069000
at batch 1070000
at batch 1071000
at batch 1072000
at batch 1073000
at batch 1074000
at batch 1075000
at batch 1076000
at batch 1077000
at batch 1078000
at batch 1079000
at batch 1080000
at batch 1081000
at batch 1082000
at batch 1083000
at batch 1084000
at batch 1085000
at batch 1086000
at batch 1087000
at batch 1088000
at batch 1089000
at batch 1090000
at batch 1091000
at batch 1092000
at batch 1093000
at batch 1094000
at batch 1095000
at batch 1096000
at batch 1097000
at batch 1098000
at batch 1099000
at batch 1100000
at batch 1101000
at batch 1102000
at batch 1103000
at batch 1104000
at batch 1105000
at batch 1106000
at batch 1107000
at batch 1108000
at batch 1109000
at batch 1110000
at batch 1111000
at batch 1112000
at batch 1113000
at batch 1114000
at batch 1115000
at batch 1116000
at batch 1117000
at batch 1118000
at batch 1119000
at batch 1120000
at batch 1121000
at batch 1122000
at batch 1123000
at batch 1124000
at batch 1125000
at batch 1126000
at batch 1127000
at batch 1128000
at batch 1129000
at batch 1130000
at batch 1131000
at batch 1132000
at batch 1133000
at batch 1134000
at batch 1135000
at batch 1136000
at batch 1137000
at batch 1138000
at batch 1139000
at batch 1140000
at batch 1141000
at batch 1142000
at batch 1143000
at batch 1144000
at batch 1145000
at batch 1146000
at batch 1147000
at batch 1148000
at batch 1149000
at batch 1150000
at batch 1151000
at batch 1152000
at batch 1153000
at batch 1154000
at batch 1155000
at batch 1156000
at batch 1157000
at batch 1158000
at batch 1159000
at batch 1160000
at batch 1161000
at batch 1162000
at batch 1163000
at batch 1164000
at batch 1165000
at batch 1166000
at batch 1167000
at batch 1168000
at batch 1169000
at batch 1170000
at batch 1171000
at batch 1172000
at batch 1173000
at batch 1174000
at batch 1175000
at batch 1176000
at batch 1177000
at batch 1178000
at batch 1179000
at batch 1180000
at batch 1181000
at batch 1182000
at batch 1183000
at batch 1184000
at batch 1185000
at batch 1186000
at batch 1187000
at batch 1188000
at batch 1189000
at batch 1190000
at batch 1191000
at batch 1192000
at batch 1193000
at batch 1194000
at batch 1195000
at batch 1196000
at batch 1197000
at batch 1198000
at batch 1199000
at batch 1200000
at batch 1201000
at batch 1202000
at batch 1203000
at batch 1204000
at batch 1205000
at batch 1206000
at batch 1207000
at batch 1208000
at batch 1209000
at batch 1210000
at batch 1211000
at batch 1212000
at batch 1213000
at batch 1214000
at batch 1215000
at batch 1216000
at batch 1217000
at batch 1218000
at batch 1219000
at batch 1220000
at batch 1221000
at batch 1222000
at batch 1223000
at batch 1224000
at batch 1225000
at batch 1226000
at batch 1227000
at batch 1228000
at batch 1229000
at batch 1230000
at batch 1231000
at batch 1232000
at batch 1233000
at batch 1234000
at batch 1235000
at batch 1236000
at batch 1237000
at batch 1238000
at batch 1239000
at batch 1240000
at batch 1241000
at batch 1242000
at batch 1243000
at batch 1244000
at batch 1245000
at batch 1246000
at batch 1247000
at batch 1248000
at batch 1249000
at batch 1250000
at batch 1251000
at batch 1252000
at batch 1253000
at batch 1254000
at batch 1255000
at batch 1256000
at batch 1257000
at batch 1258000
at batch 1259000
at batch 1260000
at batch 1261000
at batch 1262000
at batch 1263000
at batch 1264000
at batch 1265000
at batch 1266000
at batch 1267000
at batch 1268000
at batch 1269000
at batch 1270000
at batch 1271000
at batch 1272000
at batch 1273000
at batch 1274000
at batch 1275000
at batch 1276000
at batch 1277000
at batch 1278000
at batch 1279000
at batch 1280000
at batch 1281000
at batch 1282000
at batch 1283000
at batch 1284000
at batch 1285000
at batch 1286000
at batch 1287000
at batch 1288000
at batch 1289000
at batch 1290000
at batch 1291000
at batch 1292000
at batch 1293000
at batch 1294000
at batch 1295000
at batch 1296000
at batch 1297000
at batch 1298000
at batch 1299000
at batch 1300000
at batch 1301000
at batch 1302000
at batch 1303000
at batch 1304000
at batch 1305000
at batch 1306000
at batch 1307000
at batch 1308000
at batch 1309000
at batch 1310000
at batch 1311000
at batch 1312000
at batch 1313000
at batch 1314000
at batch 1315000
at batch 1316000
at batch 1317000
at batch 1318000
at batch 1319000
at batch 1320000
at batch 1321000
at batch 1322000
at batch 1323000
at batch 1324000
at batch 1325000
at batch 1326000
at batch 1327000
at batch 1328000
at batch 1329000
at batch 1330000
at batch 1331000
at batch 1332000
at batch 1333000
at batch 1334000
at batch 1335000
at batch 1336000
at batch 1337000
at batch 1338000
at batch 1339000
at batch 1340000
at batch 1341000
at batch 1342000
at batch 1343000
at batch 1344000
at batch 1345000
at batch 1346000
at batch 1347000
at batch 1348000
at batch 1349000
at batch 1350000
at batch 1351000
at batch 1352000
at batch 1353000
at batch 1354000
at batch 1355000
at batch 1356000
at batch 1357000
at batch 1358000
at batch 1359000
at batch 1360000
at batch 1361000
at batch 1362000

In [537]:
# some customers are not in the transactions set so let's predict some dummy predictions
not_observed_customers = set(df_cust.customer_id).difference(set(preds))

preds.update({cid: ("0637847001 " * 12).strip() for cid in not_observed_customers})

In [540]:
final = pd.Series(preds).to_frame().reset_index()

In [541]:
final.columns = ["customer_id", "prediction"]

In [544]:
final

,customer_id,prediction
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0637847001 0786925004 0607884001 0681002002 07...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0719628001 0607884001 0841565001 0732017001 07...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0902802001 0815434001 0852584001 0906576001 05...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0902802001 0906576001 0815434001 0852584001 08...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0815434001 0852584001 0906576001 0902802001 08...
...,...,...
1371975,086888283806bc0900c1b616ea516e23e056984ac62cb3...,0637847001 0637847001 0637847001 0637847001 06...
1371976,e086d1c2aa7f9b4a4c9491b5bdfdde53072ca3299df73e...,0637847001 0637847001 0637847001 0637847001 06...
1371977,ccd955136227e80c182ed8d3c27e1766fd652ef18920da...,0637847001 0637847001 0637847001 0637847001 06...
1371978,2a59a3e9dbffb25efdce6c524205b08f687d38bb410ef0...,0637847001 0637847001 0637847001 0637847001 06...
1371979,daf71565f683f5bb9d106939e6fc1ba72edb1c044155ea...,0637847001 0637847001 0637847001 0637847001 06...

In [543]:
final.to_csv("submission2.csv", index=False)